### ISSUE TITLE
Wonky keybind.

### ISSUE THREAD

**Issue by BoboSims** [mod-warriors/NotEnoughKeys#24]
I've set the O key to open the Armor interface. When NotEnoughKeys-1.7.10-1.0.0b29.jar is active, however, this key acts up: For the Armor interface to open, I need to press and hold the key, and only release it while I'm moving the mouse around. When I disable NEK, the issue resolves quietly, and the key acts as it should.

I'm running MC 1.7.10 with DireWolf20's modpack v1.0.3, to which I added the following:
- additionalpipes-3.4.jar
- backpack-2.0.1-1.7.x.jar
- logisticspipes-0.8.2.89.jar

**Comment by TheTemportalist** [comment]
Is this still an issue? I cant remember.... Im sorry...

**Comment by BoboSims** [comment]
I don't remember having seen a fix or update, so I'm still playing without NEK. Later tonight, whem I'm home, I might try and see what happens. But my setup hasn't changed, so I have little hope...
