### ISSUE TITLE
NEK breaks FZ's sprint key

### ISSUE THREAD

**Issue by purpleposeidon** [mod-warriors/NotEnoughKeys#25]
Sprinting is interrupted whenever the mouse is moved, or a key is pressed. The cause looks like it happens in KeyEvents.refreshBindings().
The relevant code on FZ's side:

    final int forwardCode = mc.gameSettings.keyBindForward.getKeyCode();
    KeyBinding.setKeyBindState(forwardCode, true);

**Comment by dmodoomsirius** [comment]
Is there anything the console is outputting?

**Comment by purpleposeidon** [comment]
There's no console output, and it does happen with just NeK and FZ.

**Comment by TheTemportalist** [comment]
Needed info:
* MC Version
* NeK Version
* What is 'FZ' ?
* FZ Version
* Does FZ implement the API
* How to reproduce bug

**Comment by Parker8283** [comment]
Factorization :P

**Comment by TheTemportalist** [comment]
Using 'Factorization-1.7.10-0.8.88.7-dev' in a development envron crashes at:
java.lang.NoSuchFieldError: canBlockGrass
	at factorization.shared.BlockFactorization.<init>(BlockFactorization.java:48) ~[BlockFactorization.class:?]

**Comment by TheTemportalist** [comment]
If you see code (https://github.com/mod-warriors/NotEnoughKeys/blob/dev/src/main/java/modwarriors/notenoughkeys/keys/KeyEvents.java#L52), what we do is check if the key is pressed. Then check if MC THINKS it is pressed. If they differ, set field to what we checked for (whether the key is down or not). If it happens to be register, then we also check if it should be pressed in regards to the modifier keys.

**Comment by Parker8283** [comment]
We use MCP snapshots, but that dev build you have isn't using the snapshots. Grab the normal build and deobf it with [BON2](https://github.com/Parker8283/BON2/releases) then use that

**Comment by TheTemportalist** [comment]
Sigh. Ok. After lunch

**Comment by TheTemportalist** [comment]
I tried deobfing. It didnt like that at all. However, NeK was running 1240, FZ 1230, so I debofed with 1230

**Comment by TheTemportalist** [comment]
I found the issue...
Unable to find method net/minecraft/client/Minecraft.func_147116_af (func_147116_af)
	at factorization.coremod.ASMTransformer.applyTransform(ASMTransformer.java:66)

**Comment by TheTemportalist** [comment]
Is Mr. Pink using ObfuscationReflectionHelper??? 0.O

**Comment by TheTemportalist** [comment]
I should say, not the issue causing the bug, but the issue causing me not being able to test

**Comment by TheTemportalist** [comment]
I do not think this is an issue, or at least have not heard anything more. This is being closed. Feel free to resubmit another issue or reopen this one if more information comes to light.
