### ISSUE TITLE
Bug: API Keybinds should not trigger when only one key is pressed

### ISSUE THREAD

**Issue by Keridos** [mod-warriors/NotEnoughKeys#26]
I have NEK and TiCon installed in my mod pack, but when I edit the TiCon Keys to use modified keys like shift or alt plus some key, they even trigger when alt or shift is not pressed, which should not happen.

**Comment by dmodoomsirius** [comment]
What version of TiCon and Nek?

**Comment by Keridos** [comment]
TConstruct-1.7.10-1.8.2a.jar
NotEnoughKeys-1.7.10-1.0.0b29.jar
