### ISSUE TITLE
special keybinding not working

### ISSUE THREAD

**Issue by Vectron** [mod-warriors/NotEnoughKeys#29]
i'm trying to implement your api, but i stumbeld onto a little odd problem.

when i set a keybind to use a modifier the keybind always works accept when i press it with the selected modifier.
and if i set it with no modifier it only works when i press a modifier.

i'm using forge 10.13.2.1240
minecraft 1.7.10
NEK 1.0.0b29
the mod i'm working on is my own branch of mapwriter 1.7.10

i also tried it with TCon 1.8.3b and this seems the have the same problem with the modifiers

**Comment by dmodoomsirius** [comment]
@TheTemportalist any clues?

**Comment by TheTemportalist** [comment]
Please point me to your forked git.

**Comment by Vectron** [comment]
https://github.com/Vectron/mapwriter/tree/master

**Comment by TheTemportalist** [comment]
https://github.com/Vectron/mapwriter/blob/master/src/main/java/mapwriter/forge/MwKeyHandler.java#L81
Look into the isPressed docs. I think that method checks how long the key is down, not if it is currently pressed down.

https://github.com/Vectron/mapwriter/blob/master/src/main/java/mapwriter/Mw.java#L692
You should probably check descriptions, but that wouldnt be causing your current issue.

Perhaps use 10.13.1.1291? That is the version NEK was build against

**Comment by Vectron** [comment]
also tried with 10.13.2.1291 but that gives the same strange behavior.

the ispressed method is the right one to use in events. it should only return true after the initial press.
atleast that's what the comment sais in 1.8 on the method.

about the description part your probably right. will change it when i get that far.
