### ISSUE TITLE
Default Keybinds

### ISSUE THREAD

**Issue by Watchful1** [mod-warriors/NotEnoughKeys#31]
One of the major problems we face at FTB is conflicting default keybinds. It's annoying for users to be forced to change keys to access functionality and we get bug reports all the time from people unable to figure it out. While NEK helps a lot with changing the keys once the player has the pack, we would love to be able to fix it from the beginning.

The problem with shipping changed default keybinds is that they are all stored in the options file, along with video and sound options, and any changes are overwritten when a new pack version is downloaded.

NEK offers very helpful import and export functions. Would it be possible to import a configuration on first load of the client? Either a config value that gets reset or possibly a way to detect the options file being created.

**Comment by TheTemportalist** [comment]
Yes, I think I can make this happen. Loading a file in the post init phase should do the trick. I will look into it hopefully this afternoon.

**Comment by TheTemportalist** [comment]
How is this?
http://gyazo.com/103c04c9cd8bda72eefee0167bafc323
