### ISSUE TITLE
GUI loop with NEI

### ISSUE THREAD

**Issue by spannerman79** [mod-warriors/NotEnoughKeys#34]
Forge 1448
MC 1.7.10
NEK version: 1.7.10-2.0.0b41

Conflict with NEI - keeps on looping "O"
Only way to resolve is to remove NEK version: 1.7.10-2.0.0b41 or downgrade to NotEnoughKeys-1.7.10-1.0.0b30.jar

**Comment by Thiana** [comment]
I'm having the same problem. Anytime the inventory is opened (via MC/Baubles/TC) it goes into a loop forcing the Tinker's Construct armor inventory open. You cant close the inventory, or switch to another inventory tab once that happens. You basically have to hit esc until you manage to get the options menu then leave the world.

**Comment by TheTemportalist** [comment]
Is this with the latest build/release?

**Comment by TheTemportalist** [comment]
I don't think 2.0.0 is the latest

**Comment by Thiana** [comment]
It's happening with b41. I'm reverting to b40 to see if the problem goes away.

**Comment by Thiana** [comment]
Latest version showing on curse is 1.7.10-2.0.0b41

**Comment by Thiana** [comment]
Happens with b40 too.

**Comment by Thiana** [comment]
With a minimal instance (NEI, Mantle, TC, NEK, Waila, CCC) the problem shows in the later betas. If you remove TC, the problem goes away. Since TC hasnt been updated recently it's probably something NEK is doing differently in b39-41

**Comment by spannerman79** [comment]
> NEK is doing differently in b39-41

Which currently via Curse the only working version (currently) is NotEnoughKeys-1.7.10-1.0.0b30

I'm willing to test b38 but I don't know where the CI or Jenkins server is located to obtain it

**Comment by TheTemportalist** [comment]
I don't know what the build server url is either. Where is my bamboo? Haha
Hopefully dmod will be able to check in until I have a chance to sit down and take a look at this. Busy IRL atm

**Comment by dmodoomsirius** [comment]
The latest thing in Build 39-41 is the api and the mod got a major version bump. I prob will talk to boni to see whats up

**Comment by TheTemportalist** [comment]
I believe this is a compatibility issue, as there was an API change which probably affected how TiCon was checking the keys. I have submitted a PR in effort to fix this.

**Comment by TheTemportalist** [comment]
I dont know if this is going to be fixed now. I tried submitting a PR, but it looks like TiCon is done updating until 1.8. Sorry for the inconvenient bugs. My PR is sitting here (https://github.com/SlimeKnights/TinkersConstruct/pull/1747) if you want to see it.

**Comment by seannyyx** [comment]
Also having issue of constant opening armour menu despite changing keep - 2.0.0b41

**Comment by Dulciphi** [comment]
I'm also replicating the issue, only with the latest version. Rolling back to NotEnoughKeys-1.7.10-1.0.0b30 sorts it.
Remapping TiCon's keys, even setting it to "none" did nothing to help.
I'm quite fine on 1.0.0b30 for now but thank you for the PR. Fingers crossed Boni gets to it.

**Comment by TheTemportalist** [comment]
Boni is no longer part of TiCon (or at least is no longer updating it)

**Comment by dmodoomsirius** [comment]
I sent boni a pm on irc that I hope he will see when he logs back in on irc.

**Comment by Thiana** [comment]
If Boni isnt working on TiCon anymore, who is?

**Comment by dmodoomsirius** [comment]
Let me see what boni says and i'll go from there.

**Comment by dmodoomsirius** [comment]
Since this is a Ticon issue and not a nek issue i'm closing this. if it needs to be reopened one of us will.

**Comment by dmodoomsirius** [comment]
I asked @TheTemportalist to reopen this issue so new issues don't continue to occur. This is not on our end this is on Tinkers end as we have stated above.

**Comment by dmodoomsirius** [comment]
Will leave open until there is a new 1.7.10 Release on 1.7.10 branch of TiCon.

**Comment by TheTemportalist** [comment]
Seems to have been fixed with the release of Tinkers Construct "1.7.10-1.8.8".
This ticket will remain open until there is sufficient testing (which I will then close) or @dmodoomsirius closes it.
