### ISSUE TITLE
Everytime return to inventory

### ISSUE THREAD

**Issue by Dream-Master** [mod-warriors/NotEnoughKeys#35]
I starting a new game in my modpack and stuck inside the inventory Menu (from Tinkers Construct). When i hit esc i get out but if i release the key I get back to the Menu. I cant move or do anything because return every time to the Inventory menu. I not configured the keys yet. I cant reach the Main menu from Minecraft hitting escape. Only be returned to the Inventory Menu from Tinkers Construct.
Tested with Version 40 and 41. With Version 30 everything be ok and normal.

Modlist:
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11403

**Comment by TheTemportalist** [comment]
This is not an issue with NEK. See https://github.com/mod-warriors/NotEnoughKeys/issues/34

**Comment by Dream-Master** [comment]
ok
