### ISSUE TITLE
Version 2.0.0b41 Causes Problem In-game

### ISSUE THREAD

**Issue by OneEye0pen** [mod-warriors/NotEnoughKeys#36]
With the newest version of your mod, released yesterday, my game became unplayable. When in game, any time I would press any key, it would open the armor inventory screen. Not exactly sure if this is because of compatibility problems with another mod or what, but I'm just letting you know everything I know.

**Comment by dmodoomsirius** [comment]
This is on tinkers construct side. We updated our Api. Review issue 34. Under closed.

**Comment by dmodoomsirius** [comment]
https://github.com/mod-warriors/NotEnoughKeys/issues/34
