### ISSUE TITLE
Inventory opened when trying to move forward

### ISSUE THREAD

**Issue by walkerjonny** [mod-warriors/NotEnoughKeys#39]
I have a weird issue. When I enter a world with this mod installed in the newest version and try to move forward the inventory opens instantly instead. When I try to close it the inventory opens nearly instantly again. This is repeatable.
This happens with the newest version NotEnoughKeys-1.7.10-2.0.0b41

**Comment by TheTemportalist** [comment]
See #34

**Comment by skaviouz** [comment]
So looking at the other issue, someone said 'Rolling back to NotEnoughKeys-1.7.10-1.0.0b30 [or until tinker's construct updates for NEK api change]'
I was about to post more details on this then I saw you post the issue link.

**Comment by dmodoomsirius** [comment]
Yes that is the only fix until that pr is pulled in....
