### ISSUE TITLE
[1.8.9] Wrong Minecraft version for notenoughkeys

### ISSUE THREAD

**Issue by freyquency** [mod-warriors/NotEnoughKeys#44]
NEK won't prevents loading in a 1.8.9 instance. Using Forge 11.15.0.1715.

**Comment by dmodoomsirius** [comment]
I do not have a compiled version of NEK for 1.8.9 if you are looking at bot.notenoughmods.com i commented saying I had to remove that version. curseforge also tells you that the mods are only 1.8.8. I will try to have a build out for 1.8.9 soon now that my gradle scripts are done.

**Comment by dmodoomsirius** [comment]
1.8.9 version has been released.

**Comment by freyquency** [comment]
Already downloaded, thanks!
