### ISSUE TITLE
Game crash pressing any key

### ISSUE THREAD

**Issue by Eufranio** [mod-warriors/NotEnoughKeys#49]
Crash-report: http://hastebin.com/midunaqivi.sql

NEK v1.7.10-3.0.0.b45
Forge 1614
Minecraft 1.7.10

**Comment by dmodoomsirius** [comment]
Does this happen with only NEK and forge? no other mods?

**Comment by dmodoomsirius** [comment]
Please reupload the crash report. As i am unable to see the current crash report. If you are able to reprodude that crash with the latest version please feel free to reopen this issue.
