### ISSUE TITLE
Game Crash (See all Buttons)

### ISSUE THREAD

**Issue by Ranaida** [mod-warriors/NotEnoughKeys#50]
The first time the game crashed was when I wanted to look up all the controlls to figure out why some items went missing from creative mode. When I click "All" the game crashes with this:
https://hastebin.com/itubovemun.php
No crash whey I try to look the conflicting ones up.
Then I decided to "uninstall" NEK 'cause I don't need that and now everytime I try to load or generate a world minecraft crashes with this:
https://hastebin.com/yofepesaju.coffeescript

**Comment by dmodoomsirius** [comment]
I can not see those crash reports. if you are able please repaste them and post again. until then i am going to close the issue. please feel free to reopen the issue if you are able to reproduce them.
